### ISSUE TITLE
Error while upgrading to 2.3.0

### ISSUE THREAD

**Issue by SnejPro** [knadh/listmonk#1069]
**Version:**
 - listmonk: v2.3.0 (dockeR)
 - OS: Debian

**Description of the bug and steps to reproduce:**
1. pull latest docker image
2. perform upgrade via `docker-compose run --rm app ./listmonk --upgrade`
3. Error
```
2022/11/29 12:19:57 main.go:97: v2.3.0 (448f0e3 2022-11-27T17:52:51Z)
2022/11/29 12:19:57 init.go:132: reading config: config.toml
2022/11/29 12:19:57 init.go:259: connecting to db: listmonk_db:5432/listmonk
** IMPORTANT: Take a backup of the database before upgrading.
continue (y/n)?  y
2022/11/29 12:19:59 upgrade.go:68: running migration v2.3.0
2022/11/29 12:19:59 upgrade.go:70: error running migration v2.3.0: pq: insert or update on table "campaigns" violates foreign key constraint "campaigns_archive_template_id_fkey"

```

**Screenshots:**

**Comment by knadh** [comment]
Ouch, I think I realise what the issue is. Can you confirm if you have a template with `id=1`? If not, can you clone an existing template and set its ID to 1?

`UPDATE templates SET id=1 WHERE id=YournewlyCreatedId`;

**Comment by SnejPro** [comment]
> Ouch, I think I realise what the issue is. Can you confirm if you have a template with `id=1`? If not, can you clone an existing template and set its ID to 1?
> 
> `UPDATE templates SET id=1 WHERE id=YournewlyCreatedId`;

That worked, thank you!

**Comment by henk23** [comment]
Same problem here. Same solution worked. 👍

**Comment by jorge-vitrubio** [comment]
Same problem here today
 - with [listmonk_2.3.0_linux_amd64.tar.gz](https://github.com/knadh/listmonk/releases/download/v2.3.0/listmonk_2.3.0_linux_amd64.tar.gz) 
 - in Debian 11 Bullseye
 - upgrading from [Listmonk 2.2.0](https://github.com/knadh/listmonk/releases/tag/v2.2.0) 

How or where do I apply?

`UPDATE templates SET id=1 WHERE id=YournewlyCreatedId;`

**Comment by NicoHood** [comment]
Will this get fixed in an upcoming updater? I did not yet upgrade because of that reason

**Comment by knadh** [comment]
@NicoHood, yes. You can create a template, set its ID to 1 and upgrade safely right now too.

**Comment by jorge-vitrubio** [comment]
> @jorge-vitrubio sorry, missed your comment. Were you able to fix this?

sorry @knadh ... me too, a bit late.

yes, I did apply that rule inside the postgree db `psql` command.

thank you

**Comment by jacotec** [comment]
@knadh Sorry to jump into an already closed issue, but I ran into this while wanting to upgrade from 2.2.0 to 2.4.0 - the issue still happens.

After searching around I gave up and restored the last backup - I have no clue where I can see the ID of my templates nor where I can change it to "1"? I have one unused template I could use - but no idea where to find the adjustment for the ID so the upgrade runs fine.
