### ISSUE TITLE
User not unsubscribed when clicking unsubscibe button in opt-in mail

### ISSUE THREAD

**Issue by cebner-proxmox** [knadh/listmonk#1515]
**Version:**
 - listmonk: v2.5.1
 - OS: Debian 12.1

**Description of the bug and steps to reproduce:**
A user subscribes to a newsletter and confirms the subscription via the link in the opt-in Email. After successful subscription, the user is listed as enabled and subscribed.

Following the unsubscribe link from the same opt-in Email, the user is presented with the Unsubscribe form, but is not unsubscribed from any newsletter when clicking on the Unsubscribe button.

This happens independent of the settings configured under `Setting > Privacy > Allow preference changes` .

Only if the user is allowed to de-select the mailing lists by manage the preferences, he can unsubscribe from the list.

**Comment by knadh** [comment]
I was able to reproduce this issue. This is because un-subscriptions currently tied to campaign UUIDs (and lists on a campaign are resolved internally). Notice the `000-0000 ...` campaign UUID in the URL. For this particular usecase, where a user is allowed to block themselves from a mailing list when they get an opt-in e-mail which they don't want to confirm, wondering what could be a meaningful route.

- Unsub links from opt-in pages only allow the "block me out of everything" option.
- They specifically unsubscribe the user from the particular list.
- Use the existing manage option to show the selection of current subscriptions which the user can then manage (this will require "Enable preference changes" to be turned on)

**Comment by cebner-proxmox** [comment]
Hi @knadh,
thank you for looking into this. From an user facing perspective I would argue that by clicking the Unsubscribe button after following the link in the email, the subscriber expects to be unsubscribed from this particular mailing list, with the option to resubscribe in the future. Especially since the button label states Unsubscribe and not block me.

Blocking the subscriber is not a good option here, as then it is not possible to resubscribe to the list again if wanted.

**Comment by knadh** [comment]
This turned out to be a tricky one. The unsub links in listmonk are campaign based, making the opt-in unsub form dysfunctional except for a) blocklisting b) using the "manage preferences" link to individually manage subscriptions.

Changed the unsub link in the e-mail to directly open the manage page for now.

![image](https://github.com/knadh/listmonk/assets/547147/b80cf7dd-5f64-470b-9f60-000e245f75fc)

**Comment by MaximilianKohler** [comment]
IMO it should still have a checkbox to blocklist as well, instead of only unchecking individual lists. 

Also, that would be a fix for #1454.
